-- Création BDD
-- CREATE DATABASE db_name COLLATE utf8_general_ci;
-- USE db_name;

BEGIN;
DROP TABLE IF EXISTS user, publication_details, publication_text, typology, genre;

CREATE TABLE IF NOT EXISTS user (
    USER_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USER_ROLE ENUM ('Lecteur', 'Auteur', 'Modérateur', 'Administrateur') NOT NULL DEFAULT 'Lecteur',  
    USER_MAIL VARCHAR(150) NOT NULL,
    USER_PASSWORD VARCHAR(300) NOT NULL, 
    USER_PSEUDO VARCHAR(50) NOT NULL,
    USER_FIRSTNAME VARCHAR(50), 
    USER_LASTNAME VARCHAR(50), 
    USER_BIRTHDATE DATE, 
    USER_DESCRIPTION TEXT, 
    USER_RANK ENUM ('Poids plume', 'Plume montante', 'Plume acérée') NOT NULL DEFAULT 'Poids plume'
) ENGINE = InnoDb; 

CREATE TABLE IF NOT EXISTS publication_details (
    PUBLICATION_ID_DETAILS INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    AUTHOR_ID INT NOT NULL,
    PUBLICATION_TITLE VARCHAR(200) NOT NULL, 
    RATINGS INT
) ENGINE = InnoDb; 

CREATE TABLE IF NOT EXISTS publication_text (
    PUBLICATION_ID_TEXT INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    AUTHOR_ID INT NOT NULL,
    PUBLICATION_CONTENT TEXT NOT NULL, 
    CHAPTERING INT
) ENGINE = InnoDb;

CREATE TABLE IF NOT EXISTS typology (
    TYPOLOGY_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    TYPOLOGY_LABEL VARCHAR(100) NOT NULL
) ENGINE = InnoDb;

CREATE TABLE IF NOT EXISTS genre (
    GENRE_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    GENRE_LABEL VARCHAR(100) NOT NULL
) ENGINE = InnoDb;

CREATE TABLE IF NOT EXISTS institutions (
    INSTITUTION_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    INSTITUTION_LABEL VARCHAR(100) NOT NULL
) ENGINE = InnoDb;


-- ajout clés étrangères --


ALTER TABLE publication_details 
    ADD CONSTRAINT Fk_PubDetailsAuthor
    FOREIGN KEY (AUTHOR_ID)
    REFERENCES user(USER_ID)
    ON DELETE CASCADE;

ALTER TABLE publication_text 
    ADD CONSTRAINT Fk_PubTextAuthor
    FOREIGN KEY (AUTHOR_ID)
    REFERENCES publication_details(AUTHOR_ID)
    ON DELETE CASCADE;


-- manque tables de liaison -- 
    
-- genre / publis -- 

CREATE TABLE genre_publications (
    GEPU_GENRE_ID INT NOT NULL ,
    GEPU_PUBLICATION_ID INT NOT NULL,
    PRIMARY  KEY (GEPU_GENRE_ID, GEPU_PUBLICATION_ID)
) ENGINE = InnoDb;

ALTER TABLE genre_publications 
    ADD CONSTRAINT Fk_Gepu_GenreId
    FOREIGN KEY (GEPU_GENRE_ID)
    REFERENCES genre(GENRE_ID)
    ON DELETE CASCADE;

ALTER TABLE genre_publications 
    ADD CONSTRAINT Fk_Gepu_PubID
    FOREIGN KEY (GEPU_PUBLICATION_ID)
    REFERENCES publication_details(PUBLICATION_ID_DETAILS)
    ON DELETE CASCADE;


-- typologie / publis -- 

CREATE TABLE typology_publications (
    TYPU_TYPOLOGY_ID INT NOT NULL, 
    TYPU_PUBLICATION_ID INT NOT NULL, 
    PRIMARY KEY (TYPU_TYPOLOGY_ID, TYPU_PUBLICATION_ID)
) ENGINE = InnoDb;

ALTER TABLE typology_publications
    ADD CONSTRAINT Fk_Typu_TypId
    FOREIGN KEY (TYPU_TYPOLOGY_ID)
    REFERENCES typology(TYPOLOGY_ID)
    ON DELETE CASCADE;

ALTER TABLE typology_publications
    ADD CONSTRAINT Fk_Typu_Pubid
    FOREIGN KEY (TYPU_PUBLICATION_ID)
    REFERENCES publication_details(PUBLICATION_ID_DETAILS)
    ON DELETE CASCADE;

COMMIT;